### ISSUE TITLE
Some question about the response from LLM.

### ISSUE THREAD

**Issue by Vanessa-ZZZ** [XiaoxinHe/TAPE#11]
Hello, I would like to ask about the result. I used the prediction result of LLM (cora dataset) you provided to calculate the accuracy. Whether using the original LLM response file or the csv file you processed, the accuracy rate is only about 16%. No such results appear for other datasets (pubmed, arxiv, and products).
Thanks so much for answering my questions!

**Comment by XiaoxinHe** [comment]
Hi,


If you want to calculate the accuracy based on the CSV file directly, since there is a label shift by one (check code [here](https://github.com/XiaoxinHe/TAPE/blob/1821dddfd030793ecbe10e6f32f0476e0cb671c4/core/data_utils/load.py#L22)), you need to manually subtract one.


Here is the example code to calculate the zero-shot accuracy of GPT:
```
from core.data_utils.load import load_gpt_preds
from core.data_utils.load import load_data

dataset = 'cora'

data, num_classes,  = load_data(dataset, use_text=False)
topk = 3 if dataset == 'pubmed' else 5
pred = load_gpt_preds(dataset, topk) - 1

acc = (pred[:, 0] == data.y.squeeze()).sum()/len(data.y.squeeze())
print(f'Acurracy: {acc:.4f}')

```

If you want to calculate the accuracy based on the GPT responses, here is an example code:
```
import numpy as np
import re
from core.data_utils.load import load_data

dataset = 'cora'
data, num_classes, text = load_data(dataset, use_text=True, use_gpt=True)

classes = [
    'Case Based', 'Genetic Algorithms', 'Neural Networks',
    'Probabilistic Methods', 'Reinforcement Learning', 'Rule Learning',
    'Theory'
]
class_str = ', '.join(classes)
class_map = {x: i for i, x in enumerate(classes)}
classes_regex = '(' + '|'.join(classes) + ')'
pred = []
cnt = 0
for p in text:
    p = p.split('.')[0]
    matches = re.findall(classes_regex, p.strip())
    mapped = [class_map[m] for m in matches]
    if len(mapped) == 0:
        # print("EMPTY: ", p)
        mapped = [1]
        cnt += 1
    pred.append(mapped)

first_pred = [p[0] for p in pred]

labels = data.y.squeeze()
acc = (labels.numpy() == first_pred).sum()/len(labels)
print(f'Acurracy: {acc:.4f}')

```

Expected output:

<img width="709" alt="Screenshot 2023-12-12 at 11 42 22" src="https://github.com/XiaoxinHe/TAPE/assets/48676630/89c3f4c2-4954-43e6-9d0d-eb897c3cf2ac">

<img width="664" alt="Screenshot 2023-12-12 at 11 43 05" src="https://github.com/XiaoxinHe/TAPE/assets/48676630/ea6a4e86-ec85-480f-ac61-81908128775b">

Hope this helps!
