### ISSUE TITLE
Question about the features when feature_type is 'TA' on cora dataset

### ISSUE THREAD

**Issue by 1957787636** [XiaoxinHe/TAPE#15]
Hi, after tuning the LLM by runing trainLM.py, on cora dataset, when I set feture_type is "TA", all the values of the features is 0. Moreover, the performance of models is low.
<img width="395" alt="image" src="https://github.com/XiaoxinHe/TAPE/assets/59616556/f84654aa-0a25-4ea0-8c71-6fdff3a14e12">
<img width="1196" alt="image" src="https://github.com/XiaoxinHe/TAPE/assets/59616556/dc9c5f9a-26e7-4649-86ab-90661bb6ca5f">

**Comment by 1957787636** [comment]
It is possible that not all features are 0 under different seed, because the performance is norm under some seeds, but the variance is large.
<img width="762" alt="image" src="https://github.com/XiaoxinHe/TAPE/assets/59616556/93390493-f34e-4ddf-b970-a20bfe6bbc9e">

**Comment by XiaoxinHe** [comment]
Hi,

I didn't see the same error from my side. Both the accuracy and the variance are decent.

<img width="1158" alt="Screenshot 2024-03-15 at 16 57 24" src="https://github.com/XiaoxinHe/TAPE/assets/48676630/fe61a99c-d059-4f49-948d-ca59e3e77e28">


And the features (using TA) should look like this:
<img width="839" alt="Screenshot 2024-03-16 at 12 02 15" src="https://github.com/XiaoxinHe/TAPE/assets/48676630/fadf06d4-ce47-4b96-b282-e0b598616678">

Therefore, the problem you encounter might be caused by the fine-tuning LM step. I suggest you check if that step was implemented correctly.

Thanks.
