### ISSUE TITLE
The num_classes of arxiv_2023 dataset is not 40

### ISSUE THREAD

**Issue by 1957787636** [XiaoxinHe/TAPE#19]
Hi, I find that the num_classes of arxiv_2023 dataset is not 40, class 0 and 19 should be missing.
<img width="876" alt="image" src="https://github.com/XiaoxinHe/TAPE/assets/59616556/675d244d-ed58-4f5e-b184-23f57997eabe">

**Comment by XiaoxinHe** [comment]
Yes, because the dataset includes papers published from January 2023 to October 2023, it is possible that some categories are not covered. However, to maintain consistency with ogbn-arxiv, we still keep the number of classes at 40. For more details about the dataset, please check this repo: https://github.com/1957787636.
