### ISSUE TITLE
environment error cuda  

### ISSUE THREAD

**Issue by zhangyue2000512** [XiaoxinHe/TAPE#8]
Why is cuda incorrect according to the environment you installed, torch. cuda. is_ Availalabel() is False

**Comment by XiaoxinHe** [comment]
Hi,

Could you please provide more details about the issue you encounter, such as your inputs and the log at the terminal so that I can pinpoint the issue?

For your reference, the expected output should be:
![Screenshot 2023-10-24 at 10 18 55](https://github.com/XiaoxinHe/TAPE/assets/48676630/ab123b8a-df17-4afb-8eee-4642345dcdf8)

**Comment by XiaoxinHe** [comment]
Please feel free to reopen the issue if you have further questions.
